#!/usr/bin/python3.5
# -*- coding: utf8 -*-
"""
BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
Innovation implementation : © Jean Portemer <jportemer@gmail.com>

This file is design to produce hard css code to be appended into innovation.js, in order to manage sprite management using HTML classes and fonts.
It works with a Python interpreter (version >= 3.5).
The generated file is created or recreated in the same folder this script is executed, its name is :
to_be_appended_into_innovation.css
"""

import os

# File the CSS code will be written in
dest_file = "to_be_appended_into_innovation.css"

def write_font_sizes(f):
	for s in range(1, 31):
		remSize = (s * 0.0625)
		f.write(""".font_size_{s} <
\tfont-size: {remSize}rem;
>\n\n""".format(s=s,remSize=remSize).replace('<', '{').replace('>', '}'))

def write_hexagon_icons(f, size, x, y, offset):
	x_reset = x
	
	# Base cards
	for id in range(0,105):
		f.write(""".{size}.hexagon_card_icon.hexagon_icon_{id} <
\tbackground-position: -{x}px -{y}px;
>\n\n""".format(size=size, id=id, x=x, y=y).replace('<', '{').replace('>', '}'))
		
		if id >= 14 and (id - 14) % 10 == 0: # New line on sprite
			x = x_reset
			y += offset
		else: # Same line, next card 
			x += offset

	# Artifact cards
	for id in range(110,215):
		f.write(""".{size}.hexagon_card_icon.hexagon_icon_{id} <
\tbackground-position: -{x}px -{y}px;
>\n\n""".format(size=size, id=id, x=x, y=y).replace('<', '{').replace('>', '}'))
		
		if id >= 124 and (id - 124) % 10 == 0: # New line on sprite
			x = x_reset
			y += offset
		else: # Same line, next card 
			x += offset

if __name__ == "__main__":
	with open(os.path.join(os.path.dirname(__file__), dest_file), "w") as f:
		f.write("/* Auto-generated by css_generator.py (Python script) */\n\n")
		write_font_sizes(f)
		write_hexagon_icons(f, "M", 3, 3, 49)
		write_hexagon_icons(f, "L", 8, 8, 101)
